# Generated by Django 5.0.2 on 2024-02-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='group',
            name='min_users',
        ),
        migrations.AddField(
            model_name='product',
            name='max_users_in_group',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_users_in_group',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
