# Generated by Django 5.0.2 on 2024-02-29 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_product_max_users_in_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='current_users',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='student_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
