# Generated by Django 5.0.2 on 2024-02-29 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_group_student_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='student_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
