# Generated by Django 5.0.2 on 2024-02-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_group_student_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupMembership',
        ),
    ]
