# Generated by Django 5.0.2 on 2024-02-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_student_studentproduct_product_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name_student',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='student_count',
            field=models.IntegerField(default=1),
        ),
    ]
