# Generated by Django 5.0.2 on 2024-02-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_group_name_student_alter_group_student_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
    ]
