# Generated by Django 5.0.2 on 2024-02-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_group_student_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name_student',
            field=models.CharField(max_length=1000),
        ),
    ]
