# Generated by Django 5.0.2 on 2024-02-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_group_name_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name_student',
            new_name='student_names',
        ),
    ]
