# Generated by Django 5.0.2 on 2024-02-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_name_student_group_student_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_users_in_group',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_users_in_group',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
