# Generated by Django 5.0.2 on 2024-02-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_product_max_users_in_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_users_in_group',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
