# Generated by Django 5.0.2 on 2024-03-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_product_max_users_in_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproduct',
            name='name_student',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
