# Generated by Django 5.0.2 on 2024-03-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_studentproduct_name_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='student_names',
            field=models.JSONField(default=list),
        ),
    ]
