# Generated by Django 5.0.2 on 2024-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_group_student_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=777),
            preserve_default=False,
        ),
    ]
